# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pcristin <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/02/14 09:31:54 by pcristin          #+#    #+#              #
#    Updated: 2019/02/14 17:06:50 by pcristin         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ./ft_display_file

all: $(NAME)
$(NAME):	
	gcc  ./main.c ./erorrs.c ./ft_putchar.c -o $(NAME)

clean: 
	rm -f *.o

fclean: clean
	rm -f $(NAME) 
